name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v4
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
      - name: Lint OpenAPI file
        run: redocly lint ./src/openAPI.yaml